### ISSUE TITLE
I would like to know how to set the test parameters in demo.yml. 

### ISSUE THREAD

**Issue by SII-YDD** [YichiCS/Diffusion-Noise-Feature#1]
I would like to know how to set the test parameters in demo.yml. After I set the temp myself, the following problems will occur.

RuntimeError: unable to mmap 106496 bytes from file <./output/lsun/real>: No such device (19)

It seems to be an internal mapping issue

**Comment by YichiCS** [comment]
Hello, I refactored the code recently, perhaps you will like it.
