### ISSUE TITLE
Can not download dataset 

### ISSUE THREAD

**Issue by hhhheep** [YichiCS/Diffusion-Noise-Feature#5]
I would like to download the dataset you provided,
 but the link you provided seems to be broken (rec is not available for us to use)
 can you update your link, thanks!

**Comment by YichiCS** [comment]
Hello, the dataset is provided by https://github.com/ZhendongWang6/DIRE. But I may upload a backup of my dataset at the end of June as my server is under maintenance..

**Comment by hhhheep** [comment]
> Hello, the dataset is provided by https://github.com/ZhendongWang6/DIRE. But I may upload a backup of my dataset at the end of June as my server is under maintenance..

Thank you will upload the backup data, I will wait for it ψ(｀∇´)ψ

**Comment by aditipanda** [comment]
@YichiCS Thank you, I'm waiting for your upload as well!

**Comment by aditipanda** [comment]
@hhhheep You can actually download the DiffusionForensics dataset from https://github.com/ZhendongWang6/DIRE - they provide a RecDrive link with code = dire. It can be found in the News Section - I just downloaded it myself :')
