### ISSUE TITLE
Evaluation on my own dataset

### ISSUE THREAD

**Issue by aditipanda** [YichiCS/Diffusion-Noise-Feature#6]
Is there a .py file for evaluation of other datasets? Demo.py is not suited for this I guess?

**Comment by YichiCS** [comment]
`eval.py` provide the function of testing your model on certain datset, you can run the command below:
```
python eval.py --dataroot $PATH_TO_DATASET --model_path $PATH_TO_MODEL
```
Certainly, you should place your dataset in the specified manner, you can refer to CNNDection, as this code is based on a rewrite of CNNDetection.
